// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWKT

/// Database is the container of tables.
public struct Database: Codable, Equatable, GoogleCloudWKT._AnyPackable,
  Sendable
{
  /// Output only. The resource name.
  /// Format:
  /// projects/{project_id_or_number}/locations/{location_id}/catalogs/{catalog_id}/databases/{database_id}
  public var name: Swift.String = Swift.String()

  /// Output only. The creation time of the database.
  public var createTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The last modification time of the database.
  public var updateTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The deletion time of the database. Only set after the database
  /// is deleted.
  public var deleteTime: GoogleCloudWKT.Timestamp? = nil

  /// Output only. The time when this database is considered expired. Only set
  /// after the database is deleted.
  public var expireTime: GoogleCloudWKT.Timestamp? = nil

  /// The database type.
  public var type: Database.Type_ = Database.Type_()

  /// Options specified for the database type.
  public var options: OneOf_Options? = nil

  /// Initialize a new instance of `Database`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = Database().with { $0.hiveOptions = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private enum CodingKeys: Swift.String, CodingKey {
    case hiveOptions = "hiveOptions"
    case name = "name"
    case createTime = "createTime"
    case updateTime = "updateTime"
    case deleteTime = "deleteTime"
    case expireTime = "expireTime"
    case type = "type"
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    self.name = try container.decode(Swift.String.self, forKey: .name)
    self.createTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .createTime)
    self.updateTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .updateTime)
    self.deleteTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .deleteTime)
    self.expireTime = try container.decodeIfPresent(
      GoogleCloudWKT.Timestamp.self, forKey: .expireTime)
    self.type = try container.decode(Database.Type_.self, forKey: .type)

    var options: OneOf_Options? = nil
    let optionsCheckAndSet = {
      if options != nil {
        throw DecodingError.dataCorrupted(
          DecodingError.Context(
            codingPath: decoder.codingPath,
            debugDescription: "Multiple values set for oneof 'options'"))
      }
      options = $0
    }
    if let hiveOptions = try container.decodeIfPresent(
      HiveDatabaseOptions?.self, forKey: .hiveOptions)
    {
      try optionsCheckAndSet(.hiveOptions(hiveOptions))
    }
    self.options = options
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.name, forKey: .name)
    try container.encode(self.createTime, forKey: .createTime)
    try container.encode(self.updateTime, forKey: .updateTime)
    try container.encode(self.deleteTime, forKey: .deleteTime)
    try container.encode(self.expireTime, forKey: .expireTime)
    try container.encode(self.type, forKey: .type)

    if let choice = self.options {
      switch choice {
      case .hiveOptions(let value):
        try container.encode(value, forKey: .hiveOptions)
      }
    }
  }

  /// The database type.
  public enum Type_: Codable, Equatable, Sendable {
    /// The type is not specified.
    case unspecified
    /// Represents a database storing tables compatible with Hive Metastore
    /// tables.
    case hive
    /// Encodes an unknown integer value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownIntValue(Int)
    /// Encodes an unknown string value.
    ///
    /// The most common cause for an unknown values is for the service to send
    /// a value unknown to the library. We recommend you update your library to
    /// the latest version.
    case unknownStringValue(String)

    public init() {
      self = .unspecified
    }

    /// Returns the integer value associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown string value, this returns `nil`.
    public var intValue: Int? {
      switch self {
      case .unspecified: return 0
      case .hive: return 1
      case .unknownIntValue(let v): return v
      case .unknownStringValue: return nil
      }
    }

    /// Returns the string value (or name) associated with the enumeration.
    ///
    /// If the enumeration was initialized with an unknown integer value, this returns `nil`.
    public var stringValue: Swift.String? {
      switch self {
      case .unspecified: return "TYPE_UNSPECIFIED"
      case .hive: return "HIVE"
      case .unknownIntValue: return nil
      case .unknownStringValue(let v): return v
      }
    }

    /// Initialize from a string value.
    ///
    /// If the value is unknown, this initializes to [`unknownStringValue`](doc:Type_/unknownStringValue(_:)).
    public init(stringValue: Swift.String) {
      switch stringValue {
      case "TYPE_UNSPECIFIED": self = .unspecified
      case "HIVE": self = .hive
      default: self = .unknownStringValue(stringValue)
      }
    }

    /// Initialize from an integer value.
    ///
    /// If the value is unknown, this initializes to [`unknownIntValue`](doc:Type_/unknownIntValue(_:)).
    public init(intValue: Int) {
      switch intValue {
      case 0: self = .unspecified
      case 1: self = .hive
      default: self = .unknownIntValue(intValue)
      }
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.singleValueContainer()
      if let v = try? container.decode(Int.self) {
        self.init(intValue: v)
        return
      }
      if let s = try? container.decode(String.self) {
        if let v = Int(s) {
          self.init(intValue: v)
        } else {
          self.init(stringValue: s)
        }
        return
      }
      throw DecodingError.dataCorruptedError(
        in: container, debugDescription: "Expected enum value, must be integer or string.")
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.singleValueContainer()
      switch self {
      case .unspecified: return try container.encode(0)
      case .hive: return try container.encode(1)
      case .unknownIntValue(let v): return try container.encode(v)
      case .unknownStringValue(let v): return try container.encode(v)
      }
    }
  }

  /// Options specified for the database type.
  public enum OneOf_Options: Codable, Equatable, Sendable {
    /// Options of a Hive database.
    indirect case hiveOptions(HiveDatabaseOptions?)
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.biglake.v1.Database"
  }
  public init(fromAny any: GoogleCloudWKT.`Any`) throws {
    self = try GoogleCloudWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWKT.Struct {
    return try GoogleCloudWKT._slowAnySerialize(message: self)
  }
}
