// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) public import GoogleWKT

/// Options of a Hive table.
public struct HiveTableOptions: Codable, Equatable, GoogleWKT._AnyPackable,
  Sendable
{
  /// Stores user supplied Hive table parameters.
  public var parameters: [Swift.String: Swift.String] = [:]

  /// Hive table type. For example, MANAGED_TABLE, EXTERNAL_TABLE.
  public var tableType: Swift.String = Swift.String()

  /// Stores physical storage information of the data.
  public var storageDescriptor: HiveTableOptions.StorageDescriptor? = nil

  @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

  /// Initialize a new instance of `HiveTableOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HiveTableOptions().with { $0.parameters = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  private struct CodingKeys: CodingKey {
    var stringValue: Swift.String
    var intValue: Swift.Int? { nil }
    init(stringValue: Swift.String) { self.stringValue = stringValue }
    init?(intValue: Swift.Int) { nil }

    static let parameters = CodingKeys(stringValue: "parameters")
    static let tableType = CodingKeys(stringValue: "tableType")
    static let storageDescriptor = CodingKeys(stringValue: "storageDescriptor")

    static let _knownKeys: Set<Swift.String> = [
      "parameters",
      "tableType",
      "storageDescriptor",
    ]
  }

  public init(from decoder: Decoder) throws {
    let container = try decoder.container(keyedBy: CodingKeys.self)
    if let value = try container.decodeIfPresent(
      [Swift.String: Swift.String].self, forKey: .parameters)
    {
      self.parameters = value
    }
    if let value = try container.decodeIfPresent(Swift.String.self, forKey: .tableType) {
      self.tableType = value
    }
    self.storageDescriptor = try container.decodeIfPresent(
      HiveTableOptions.StorageDescriptor.self, forKey: .storageDescriptor)
    for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
      self._unknownFields.json[key.stringValue] = try container.decode(
        GoogleWKT.Value.self, forKey: key)
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.container(keyedBy: CodingKeys.self)
    try container.encode(self.parameters, forKey: .parameters)
    try container.encode(self.tableType, forKey: .tableType)
    try container.encodeIfPresent(self.storageDescriptor, forKey: .storageDescriptor)
    for (key, value) in self._unknownFields.json {
      try container.encode(value, forKey: CodingKeys(stringValue: key))
    }
  }

  /// Serializer and deserializer information.
  public struct SerDeInfo: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// The fully qualified Java class name of the serialization library.
    public var serializationLib: Swift.String = Swift.String()

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `SerDeInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SerDeInfo().with { $0.serializationLib = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let serializationLib = CodingKeys(stringValue: "serializationLib")

      static let _knownKeys: Set<Swift.String> = [
        "serializationLib"
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .serializationLib) {
        self.serializationLib = value
      }
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.serializationLib, forKey: .serializationLib)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.biglake.v1.HiveTableOptions.SerDeInfo"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  /// Stores physical storage information of the data.
  public struct StorageDescriptor: Codable, Equatable, GoogleWKT._AnyPackable,
    Sendable
  {
    /// Cloud Storage folder URI where the table data is stored, starting with
    /// "gs://".
    public var locationUri: Swift.String = Swift.String()

    /// The fully qualified Java class name of the input format.
    public var inputFormat: Swift.String = Swift.String()

    /// The fully qualified Java class name of the output format.
    public var outputFormat: Swift.String = Swift.String()

    /// Serializer and deserializer information.
    public var serdeInfo: HiveTableOptions.SerDeInfo? = nil

    @_spi(GoogleCloudInternal) public var _unknownFields: GoogleWKT._UnknownFields = .init()

    /// Initialize a new instance of `StorageDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StorageDescriptor().with { $0.locationUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    private struct CodingKeys: CodingKey {
      var stringValue: Swift.String
      var intValue: Swift.Int? { nil }
      init(stringValue: Swift.String) { self.stringValue = stringValue }
      init?(intValue: Swift.Int) { nil }

      static let locationUri = CodingKeys(stringValue: "locationUri")
      static let inputFormat = CodingKeys(stringValue: "inputFormat")
      static let outputFormat = CodingKeys(stringValue: "outputFormat")
      static let serdeInfo = CodingKeys(stringValue: "serdeInfo")

      static let _knownKeys: Set<Swift.String> = [
        "locationUri",
        "inputFormat",
        "outputFormat",
        "serdeInfo",
      ]
    }

    public init(from decoder: Decoder) throws {
      let container = try decoder.container(keyedBy: CodingKeys.self)
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .locationUri) {
        self.locationUri = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .inputFormat) {
        self.inputFormat = value
      }
      if let value = try container.decodeIfPresent(Swift.String.self, forKey: .outputFormat) {
        self.outputFormat = value
      }
      self.serdeInfo = try container.decodeIfPresent(
        HiveTableOptions.SerDeInfo.self, forKey: .serdeInfo)
      for key in container.allKeys where !CodingKeys._knownKeys.contains(key.stringValue) {
        self._unknownFields.json[key.stringValue] = try container.decode(
          GoogleWKT.Value.self, forKey: key)
      }
    }

    public func encode(to encoder: Encoder) throws {
      var container = encoder.container(keyedBy: CodingKeys.self)
      try container.encode(self.locationUri, forKey: .locationUri)
      try container.encode(self.inputFormat, forKey: .inputFormat)
      try container.encode(self.outputFormat, forKey: .outputFormat)
      try container.encodeIfPresent(self.serdeInfo, forKey: .serdeInfo)
      for (key, value) in self._unknownFields.json {
        try container.encode(value, forKey: CodingKeys(stringValue: key))
      }
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.biglake.v1.HiveTableOptions.StorageDescriptor"
    }
    public init(fromAny any: GoogleWKT.`Any`) throws {
      self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleWKT.Struct {
      return try GoogleWKT._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.biglake.v1.HiveTableOptions"
  }
  public init(fromAny any: GoogleWKT.`Any`) throws {
    self = try GoogleWKT._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleWKT.Struct {
    return try GoogleWKT._slowAnySerialize(message: self)
  }
}
