// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
@_spi(GoogleCloudInternal) import GoogleCloudWkt

/// Options of a Hive table.
public struct HiveTableOptions: Codable, Equatable, GoogleCloudWkt._AnyPackable,
  Sendable
{
  /// Stores user supplied Hive table parameters.
  public var parameters: [Swift.String: Swift.String] = [:]

  /// Hive table type. For example, MANAGED_TABLE, EXTERNAL_TABLE.
  public var tableType: Swift.String = Swift.String()

  /// Stores physical storage information of the data.
  public var storageDescriptor: HiveTableOptions.StorageDescriptor? = nil

  /// Initialize a new instance of `HiveTableOptions`.
  public init() {}

  /// Use `config` to return a new instance of this object, with some fields updated.
  ///
  /// Commonly used to initialize the value, for example:
  ///
  /// ```
  /// let value = HiveTableOptions().with { $0.parameters = ... }
  /// ```
  public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
    var copy = self
    try config(&copy)
    return copy
  }

  /// Serializer and deserializer information.
  public struct SerDeInfo: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// The fully qualified Java class name of the serialization library.
    public var serializationLib: Swift.String = Swift.String()

    /// Initialize a new instance of `SerDeInfo`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = SerDeInfo().with { $0.serializationLib = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return "type.googleapis.com/google.cloud.bigquery.biglake.v1.HiveTableOptions.SerDeInfo"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  /// Stores physical storage information of the data.
  public struct StorageDescriptor: Codable, Equatable, GoogleCloudWkt._AnyPackable,
    Sendable
  {
    /// Cloud Storage folder URI where the table data is stored, starting with
    /// "gs://".
    public var locationUri: Swift.String = Swift.String()

    /// The fully qualified Java class name of the input format.
    public var inputFormat: Swift.String = Swift.String()

    /// The fully qualified Java class name of the output format.
    public var outputFormat: Swift.String = Swift.String()

    /// Serializer and deserializer information.
    public var serdeInfo: HiveTableOptions.SerDeInfo? = nil

    /// Initialize a new instance of `StorageDescriptor`.
    public init() {}

    /// Use `config` to return a new instance of this object, with some fields updated.
    ///
    /// Commonly used to initialize the value, for example:
    ///
    /// ```
    /// let value = StorageDescriptor().with { $0.locationUri = ... }
    /// ```
    public func with(_ config: (inout Self) throws -> Swift.Void) rethrows -> Self {
      var copy = self
      try config(&copy)
      return copy
    }

    public static var _anyTypeUrl: Swift.String {
      return
        "type.googleapis.com/google.cloud.bigquery.biglake.v1.HiveTableOptions.StorageDescriptor"
    }
    public init(fromAny any: GoogleCloudWkt.`Any`) throws {
      self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
    }
    public func _pack() throws -> GoogleCloudWkt.Struct {
      return try GoogleCloudWkt._slowAnySerialize(message: self)
    }
  }

  public static var _anyTypeUrl: Swift.String {
    return "type.googleapis.com/google.cloud.bigquery.biglake.v1.HiveTableOptions"
  }
  public init(fromAny any: GoogleCloudWkt.`Any`) throws {
    self = try GoogleCloudWkt._slowAnyDeserialize(Self.self, from: any)
  }
  public func _pack() throws -> GoogleCloudWkt.Struct {
    return try GoogleCloudWkt._slowAnySerialize(message: self)
  }
}
