// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol MetastoreServiceStub: Sendable {
    func createCatalog(
      request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    func deleteCatalog(
      request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    func getCatalog(
      request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    func listCatalogs(
      request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse

    func createDatabase(
      request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func deleteDatabase(
      request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func updateDatabase(
      request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func getDatabase(
      request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func listDatabases(
      request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse

    func createTable(
      request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func deleteTable(
      request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func updateTable(
      request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func renameTable(
      request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func getTable(
      request: GetTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func listTables(
      request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse
  }
}
