// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

extension Clients {
  protocol MetastoreServiceStub {
    func createCatalog(
      request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    func deleteCatalog(
      request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    func getCatalog(
      request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    func listCatalogs(
      request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse

    func createDatabase(
      request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func deleteDatabase(
      request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func updateDatabase(
      request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func getDatabase(
      request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    func listDatabases(
      request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse

    func createTable(
      request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func deleteTable(
      request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func updateTable(
      request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func renameTable(
      request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func getTable(
      request: GetTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    func listTables(
      request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse
  }

  class MetastoreServiceTransport: MetastoreServiceStub {
    let inner: GoogleCloudGax.HTTPClient

    public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
      self.inner = try GoogleCloudGax.HTTPClient(
        from: options, withDefaultEndpoint: "https://biglake.googleapis.com")
    }

    public func createCatalog(
      request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/catalogs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.catalogId, prefix: "catalogId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.catalog {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Catalog.self, from: data)
    }

    public func deleteCatalog(
      request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Catalog.self, from: data)
    }

    public func getCatalog(
      request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Catalog.self, from: data)
    }

    public func listCatalogs(
      request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/catalogs"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.ListCatalogsResponse.self, from: data)
    }

    public func createDatabase(
      request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/databases"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.databaseId, prefix: "databaseId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.database {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Database.self, from: data)
    }

    public func deleteDatabase(
      request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Database.self, from: data)
    }

    public func updateDatabase(
      request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.database.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding(
            "'request.database.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.database {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Database.self, from: data)
    }

    public func getDatabase(
      request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Database.self, from: data)
    }

    public func listDatabases(
      request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/databases"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.ListDatabasesResponse.self, from: data)
    }

    public func createTable(
      request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/tables"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.tableId, prefix: "tableId"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.table {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Table.self, from: data)
    }

    public func deleteTable(
      request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "DELETE"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Table.self, from: data)
    }

    public func updateTable(
      request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.table.map({ $0.name }), !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.table.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.updateMask, prefix: "updateMask"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "PATCH"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      if let body = request.table {
        req.setValue("application/json", forHTTPHeaderField: "Content-Type")
        req.httpBody = try JSONEncoder().encode(body)
      }
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Table.self, from: data)
    }

    public func renameTable(
      request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0):rename"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "POST"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      req.setValue("application/json", forHTTPHeaderField: "Content-Type")
      req.httpBody = try JSONEncoder().encode(request)
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Table.self, from: data)
    }

    public func getTable(
      request: GetTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.name as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.name' is not set or is empty")
        }
        return "/v1/\(pathVariable0)"
      }()
      let query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.Table.self, from: data)
    }

    public func listTables(
      request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse {
      let path = try { () throws -> Swift.String in
        guard let pathVariable0 = request.parent as Swift.String?, !pathVariable0.isEmpty else {
          throw GoogleCloudGax.RequestError.binding("'request.parent' is not set or is empty")
        }
        return "/v1/\(pathVariable0)/tables"
      }()
      var query = [
        URLQueryItem(name: "$alt", value: "json;enum-encoding=int")
      ]
      let encoder = GoogleCloudGax.QueryParameterEncoder()
      query.append(contentsOf: try encoder.encode(request.pageSize, prefix: "pageSize"))
      query.append(contentsOf: try encoder.encode(request.pageToken, prefix: "pageToken"))
      query.append(contentsOf: try encoder.encode(request.view, prefix: "view"))
      var req = try await self.inner.Request(path: path, query: query)
      req.httpMethod = "GET"
      req.setValue(Clients.clientHeader, forHTTPHeaderField: "X-Goog-Api-Client")
      let (data, _) = try await self.inner.rpc(for: req).get()
      return try GoogleCloudWkt._ProtoJSONDecoder().decode(
        GoogleBigQueryBigLakeV1.ListTablesResponse.self, from: data)
    }
  }
}
