// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax

/// BigLake Metastore is a serverless, highly available, multi-tenant runtime
/// metastore for Google Cloud Data Analytics products.
///
/// The BigLake Metastore API defines the following resource model:
///
/// * A collection of Google Cloud projects: `/projects/*`
/// * Each project has a collection of available locations: `/locations/*`
/// * Each location has a collection of catalogs: `/catalogs/*`
/// * Each catalog has a collection of databases: `/databases/*`
/// * Each database has a collection of tables: `/tables/*`
///
/// @Snippet(path: "MetastoreServiceQuickstart")
public class MetastoreServiceClient: Clients.MetastoreServiceProtocol {
  let inner: any Clients.MetastoreServiceStub

  /// Creates a new `MetastoreServiceClient` instance.
  public init(_ options: GoogleCloudGax.ClientOptions = .init()) throws {
    var inner: any Clients.MetastoreServiceStub = try Clients.MetastoreServiceTransport(options)
    inner = Clients.MetastoreServiceRetry(inner, options: options)
    if let logger = options.logger {
      inner = Clients.MetastoreServiceLogging(inner, logger: logger)
    }
    self.inner = inner
  }

  /// Creates a new catalog.
  ///
  /// @Snippet(path: "MetastoreService_CreateCatalog")
  public func createCatalog(
    request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    try await self.inner.createCatalog(request: request, options: options)
  }

  /// Deletes an existing catalog specified by the catalog ID.
  ///
  /// @Snippet(path: "MetastoreService_DeleteCatalog")
  public func deleteCatalog(
    request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    try await self.inner.deleteCatalog(request: request, options: options)
  }

  /// Gets the catalog specified by the resource name.
  ///
  /// @Snippet(path: "MetastoreService_GetCatalog")
  public func getCatalog(
    request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    try await self.inner.getCatalog(request: request, options: options)
  }

  /// List all catalogs in a specified project.
  ///
  /// @Snippet(path: "MetastoreService_ListCatalogs")
  public func listCatalogs(
    request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse {
    try await self.inner.listCatalogs(request: request, options: options)
  }

  /// List all catalogs in a specified project.
  ///
  /// @Snippet(path: "MetastoreService_ListCatalogs")
  public func listCatalogs(
    byItem: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Catalog, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listCatalogs(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new database.
  ///
  /// @Snippet(path: "MetastoreService_CreateDatabase")
  public func createDatabase(
    request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    try await self.inner.createDatabase(request: request, options: options)
  }

  /// Deletes an existing database specified by the database ID.
  ///
  /// @Snippet(path: "MetastoreService_DeleteDatabase")
  public func deleteDatabase(
    request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    try await self.inner.deleteDatabase(request: request, options: options)
  }

  /// Updates an existing database specified by the database ID.
  ///
  /// @Snippet(path: "MetastoreService_UpdateDatabase")
  public func updateDatabase(
    request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    try await self.inner.updateDatabase(request: request, options: options)
  }

  /// Gets the database specified by the resource name.
  ///
  /// @Snippet(path: "MetastoreService_GetDatabase")
  public func getDatabase(
    request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    try await self.inner.getDatabase(request: request, options: options)
  }

  /// List all databases in a specified catalog.
  ///
  /// @Snippet(path: "MetastoreService_ListDatabases")
  public func listDatabases(
    request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse {
    try await self.inner.listDatabases(request: request, options: options)
  }

  /// List all databases in a specified catalog.
  ///
  /// @Snippet(path: "MetastoreService_ListDatabases")
  public func listDatabases(
    byItem: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Database, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listDatabases(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  /// Creates a new table.
  ///
  /// @Snippet(path: "MetastoreService_CreateTable")
  public func createTable(
    request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    try await self.inner.createTable(request: request, options: options)
  }

  /// Deletes an existing table specified by the table ID.
  ///
  /// @Snippet(path: "MetastoreService_DeleteTable")
  public func deleteTable(
    request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    try await self.inner.deleteTable(request: request, options: options)
  }

  /// Updates an existing table specified by the table ID.
  ///
  /// @Snippet(path: "MetastoreService_UpdateTable")
  public func updateTable(
    request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    try await self.inner.updateTable(request: request, options: options)
  }

  /// Renames an existing table specified by the table ID.
  ///
  /// @Snippet(path: "MetastoreService_RenameTable")
  public func renameTable(
    request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    try await self.inner.renameTable(request: request, options: options)
  }

  /// Gets the table specified by the resource name.
  ///
  /// @Snippet(path: "MetastoreService_GetTable")
  public func getTable(
    request: GetTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    try await self.inner.getTable(request: request, options: options)
  }

  /// List all tables in a specified database.
  ///
  /// @Snippet(path: "MetastoreService_ListTables")
  public func listTables(
    request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse {
    try await self.inner.listTables(request: request, options: options)
  }

  /// List all tables in a specified database.
  ///
  /// @Snippet(path: "MetastoreService_ListTables")
  public func listTables(
    byItem: ListTablesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Table, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse in
      var request = byItem
      request.pageToken = token
      return try await self.listTables(request: request, options: options)
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }
}

extension Clients {
  /// A Swift protocol to mock `MetastoreServiceClient`.
  ///
  /// To mock `MetastoreServiceClient` change your functions to receive
  /// `some MetastoreServiceProtocol` or `any MetastoreServiceProtocol`
  /// and pass a mock implementation in your tests.
  public protocol MetastoreServiceProtocol {
    /// See `MetastoreServiceClient.createCatalog`.
    func createCatalog(request: CreateCatalogRequest) async throws
      -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.createCatalog`.
    func createCatalog(
      parent: Swift.String,
      catalog: Catalog?,
      catalogId: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.deleteCatalog`.
    func deleteCatalog(request: DeleteCatalogRequest) async throws
      -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.deleteCatalog`.
    func deleteCatalog(
      name: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.getCatalog`.
    func getCatalog(request: GetCatalogRequest) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.getCatalog`.
    func getCatalog(
      name: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.listCatalogs`.
    func listCatalogs(request: ListCatalogsRequest) async throws
      -> GoogleBigQueryBigLakeV1.ListCatalogsResponse

    /// See `MetastoreServiceClient.listCatalogs`.
    func listCatalogs(
      byItem: ListCatalogsRequest
    ) throws -> any AsyncSequence<Catalog, Swift.Error>

    /// See `MetastoreServiceClient.listCatalogs`.
    func listCatalogs(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Catalog, Swift.Error>

    /// See `MetastoreServiceClient.createDatabase`.
    func createDatabase(request: CreateDatabaseRequest) async throws
      -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.createDatabase`.
    func createDatabase(
      parent: Swift.String,
      database: Database?,
      databaseId: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.deleteDatabase`.
    func deleteDatabase(request: DeleteDatabaseRequest) async throws
      -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.deleteDatabase`.
    func deleteDatabase(
      name: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.updateDatabase`.
    func updateDatabase(request: UpdateDatabaseRequest) async throws
      -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.updateDatabase`.
    func updateDatabase(
      database: Database?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.getDatabase`.
    func getDatabase(request: GetDatabaseRequest) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.getDatabase`.
    func getDatabase(
      name: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.listDatabases`.
    func listDatabases(request: ListDatabasesRequest) async throws
      -> GoogleBigQueryBigLakeV1.ListDatabasesResponse

    /// See `MetastoreServiceClient.listDatabases`.
    func listDatabases(
      byItem: ListDatabasesRequest
    ) throws -> any AsyncSequence<Database, Swift.Error>

    /// See `MetastoreServiceClient.listDatabases`.
    func listDatabases(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Database, Swift.Error>

    /// See `MetastoreServiceClient.createTable`.
    func createTable(request: CreateTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.createTable`.
    func createTable(
      parent: Swift.String,
      table: Table?,
      tableId: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.deleteTable`.
    func deleteTable(request: DeleteTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.deleteTable`.
    func deleteTable(
      name: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.updateTable`.
    func updateTable(request: UpdateTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.updateTable`.
    func updateTable(
      table: Table?,
      updateMask: GoogleCloudWkt.FieldMask?,
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.renameTable`.
    func renameTable(request: RenameTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.renameTable`.
    func renameTable(
      name: Swift.String,
      newName: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.getTable`.
    func getTable(request: GetTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.getTable`.
    func getTable(
      name: Swift.String,
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.listTables`.
    func listTables(request: ListTablesRequest) async throws
      -> GoogleBigQueryBigLakeV1.ListTablesResponse

    /// See `MetastoreServiceClient.listTables`.
    func listTables(
      byItem: ListTablesRequest
    ) throws -> any AsyncSequence<Table, Swift.Error>

    /// See `MetastoreServiceClient.listTables`.
    func listTables(
      parent: Swift.String,
    ) throws -> any AsyncSequence<Table, Swift.Error>

    /// See `MetastoreServiceClient.createCatalog`.
    func createCatalog(
      request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.deleteCatalog`.
    func deleteCatalog(
      request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.getCatalog`.
    func getCatalog(
      request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog

    /// See `MetastoreServiceClient.listCatalogs`.
    func listCatalogs(
      request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse

    /// See `MetastoreServiceClient.listCatalogs`.
    func listCatalogs(
      byItem: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Catalog, Swift.Error>

    /// See `MetastoreServiceClient.createDatabase`.
    func createDatabase(
      request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.deleteDatabase`.
    func deleteDatabase(
      request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.updateDatabase`.
    func updateDatabase(
      request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.getDatabase`.
    func getDatabase(
      request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database

    /// See `MetastoreServiceClient.listDatabases`.
    func listDatabases(
      request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse

    /// See `MetastoreServiceClient.listDatabases`.
    func listDatabases(
      byItem: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Database, Swift.Error>

    /// See `MetastoreServiceClient.createTable`.
    func createTable(
      request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.deleteTable`.
    func deleteTable(
      request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.updateTable`.
    func updateTable(
      request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.renameTable`.
    func renameTable(
      request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.getTable`.
    func getTable(
      request: GetTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table

    /// See `MetastoreServiceClient.listTables`.
    func listTables(
      request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse

    /// See `MetastoreServiceClient.listTables`.
    func listTables(
      byItem: ListTablesRequest, options: GoogleCloudGax.RequestOptions
    ) throws -> any AsyncSequence<Table, Swift.Error>
  }
}

// Default implementations
extension Clients.MetastoreServiceProtocol {
  public func createCatalog(request: CreateCatalogRequest) async throws
    -> GoogleBigQueryBigLakeV1.Catalog
  {
    try await self.createCatalog(request: request, options: .init())
  }

  public func createCatalog(
    request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createCatalog(
    parent: Swift.String,
    catalog: Catalog?,
    catalogId: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    let request = CreateCatalogRequest().with {
      $0.parent = parent
      $0.catalog = catalog
      $0.catalogId = catalogId
    }
    return try await self.createCatalog(request: request)
  }

  public func deleteCatalog(request: DeleteCatalogRequest) async throws
    -> GoogleBigQueryBigLakeV1.Catalog
  {
    try await self.deleteCatalog(request: request, options: .init())
  }

  public func deleteCatalog(
    request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteCatalog(
    name: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    let request = DeleteCatalogRequest().with {
      $0.name = name
    }
    return try await self.deleteCatalog(request: request)
  }

  public func getCatalog(request: GetCatalogRequest) async throws -> GoogleBigQueryBigLakeV1.Catalog
  {
    try await self.getCatalog(request: request, options: .init())
  }

  public func getCatalog(
    request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getCatalog(
    name: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
    let request = GetCatalogRequest().with {
      $0.name = name
    }
    return try await self.getCatalog(request: request)
  }

  public func listCatalogs(request: ListCatalogsRequest) async throws
    -> GoogleBigQueryBigLakeV1.ListCatalogsResponse
  {
    try await self.listCatalogs(request: request, options: .init())
  }

  public func listCatalogs(
    request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listCatalogs(
    byItem: ListCatalogsRequest
  ) throws -> any AsyncSequence<Catalog, Swift.Error> {
    try self.listCatalogs(byItem: byItem, options: .init())
  }

  public func listCatalogs(
    byItem: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Catalog, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listCatalogs(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Catalog, Swift.Error> {
    let request = ListCatalogsRequest().with {
      $0.parent = parent
    }
    return try self.listCatalogs(byItem: request)
  }

  public func createDatabase(request: CreateDatabaseRequest) async throws
    -> GoogleBigQueryBigLakeV1.Database
  {
    try await self.createDatabase(request: request, options: .init())
  }

  public func createDatabase(
    request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createDatabase(
    parent: Swift.String,
    database: Database?,
    databaseId: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    let request = CreateDatabaseRequest().with {
      $0.parent = parent
      $0.database = database
      $0.databaseId = databaseId
    }
    return try await self.createDatabase(request: request)
  }

  public func deleteDatabase(request: DeleteDatabaseRequest) async throws
    -> GoogleBigQueryBigLakeV1.Database
  {
    try await self.deleteDatabase(request: request, options: .init())
  }

  public func deleteDatabase(
    request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteDatabase(
    name: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    let request = DeleteDatabaseRequest().with {
      $0.name = name
    }
    return try await self.deleteDatabase(request: request)
  }

  public func updateDatabase(request: UpdateDatabaseRequest) async throws
    -> GoogleBigQueryBigLakeV1.Database
  {
    try await self.updateDatabase(request: request, options: .init())
  }

  public func updateDatabase(
    request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateDatabase(
    database: Database?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    let request = UpdateDatabaseRequest().with {
      $0.database = database
      $0.updateMask = updateMask
    }
    return try await self.updateDatabase(request: request)
  }

  public func getDatabase(request: GetDatabaseRequest) async throws
    -> GoogleBigQueryBigLakeV1.Database
  {
    try await self.getDatabase(request: request, options: .init())
  }

  public func getDatabase(
    request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getDatabase(
    name: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Database {
    let request = GetDatabaseRequest().with {
      $0.name = name
    }
    return try await self.getDatabase(request: request)
  }

  public func listDatabases(request: ListDatabasesRequest) async throws
    -> GoogleBigQueryBigLakeV1.ListDatabasesResponse
  {
    try await self.listDatabases(request: request, options: .init())
  }

  public func listDatabases(
    request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listDatabases(
    byItem: ListDatabasesRequest
  ) throws -> any AsyncSequence<Database, Swift.Error> {
    try self.listDatabases(byItem: byItem, options: .init())
  }

  public func listDatabases(
    byItem: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Database, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listDatabases(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Database, Swift.Error> {
    let request = ListDatabasesRequest().with {
      $0.parent = parent
    }
    return try self.listDatabases(byItem: request)
  }

  public func createTable(request: CreateTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table
  {
    try await self.createTable(request: request, options: .init())
  }

  public func createTable(
    request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func createTable(
    parent: Swift.String,
    table: Table?,
    tableId: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    let request = CreateTableRequest().with {
      $0.parent = parent
      $0.table = table
      $0.tableId = tableId
    }
    return try await self.createTable(request: request)
  }

  public func deleteTable(request: DeleteTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table
  {
    try await self.deleteTable(request: request, options: .init())
  }

  public func deleteTable(
    request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func deleteTable(
    name: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    let request = DeleteTableRequest().with {
      $0.name = name
    }
    return try await self.deleteTable(request: request)
  }

  public func updateTable(request: UpdateTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table
  {
    try await self.updateTable(request: request, options: .init())
  }

  public func updateTable(
    request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func updateTable(
    table: Table?,
    updateMask: GoogleCloudWkt.FieldMask?,
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    let request = UpdateTableRequest().with {
      $0.table = table
      $0.updateMask = updateMask
    }
    return try await self.updateTable(request: request)
  }

  public func renameTable(request: RenameTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table
  {
    try await self.renameTable(request: request, options: .init())
  }

  public func renameTable(
    request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func renameTable(
    name: Swift.String,
    newName: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    let request = RenameTableRequest().with {
      $0.name = name
      $0.newName = newName
    }
    return try await self.renameTable(request: request)
  }

  public func getTable(request: GetTableRequest) async throws -> GoogleBigQueryBigLakeV1.Table {
    try await self.getTable(request: request, options: .init())
  }

  public func getTable(
    request: GetTableRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func getTable(
    name: Swift.String,
  ) async throws -> GoogleBigQueryBigLakeV1.Table {
    let request = GetTableRequest().with {
      $0.name = name
    }
    return try await self.getTable(request: request)
  }

  public func listTables(request: ListTablesRequest) async throws
    -> GoogleBigQueryBigLakeV1.ListTablesResponse
  {
    try await self.listTables(request: request, options: .init())
  }

  public func listTables(
    request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
  ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse {
    throw GoogleCloudGax.RequestError.unimplemented
  }

  public func listTables(
    byItem: ListTablesRequest
  ) throws -> any AsyncSequence<Table, Swift.Error> {
    try self.listTables(byItem: byItem, options: .init())
  }

  public func listTables(
    byItem: ListTablesRequest, options: GoogleCloudGax.RequestOptions
  ) throws -> any AsyncSequence<Table, Swift.Error> {
    let listRpc = {
      (token: Swift.String) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse in
      throw GoogleCloudGax.RequestError.unimplemented
    }
    return GoogleCloudGax.PaginatedResponseSequence(listRpc: listRpc)
  }

  public func listTables(
    parent: Swift.String,
  ) throws -> any AsyncSequence<Table, Swift.Error> {
    let request = ListTablesRequest().with {
      $0.parent = parent
    }
    return try self.listTables(byItem: request)
  }
}
