// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleCloudWkt
import GoogleCloudGax
import struct Logging.Logger

extension Clients {
  final class MetastoreServiceLogging: MetastoreServiceStub {
    let inner: any MetastoreServiceStub
    let logger: Logger

    public init(_ inner: any MetastoreServiceStub, logger: Logger) {
      var logger = logger
      logger[metadataKey: "gcp.artifact.id"] = "google-cloud-bigquery-biglake-v1"
      logger[metadataKey: "gcp.client.service"] = "biglake"
      logger[metadataKey: "gcp.experimental.swift.client"] = "MetastoreService"
      self.inner = inner
      self.logger = logger
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleCloudGax.RequestOptions,
      name: Swift.String,
      action: (Input, GoogleCloudGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      var logger = logger
      logger[metadataKey: "gcp.experimental.swift.request.id"] = "\(UUID())"
      logger[metadataKey: "gcp.experimental.swift.method"] = .string(name)
      logger.debug("enter  : \(request) \(options)")
      do {
        let output = try await action(request, options)
        logger.debug("success: \(request) \(options) \(output)")
        return output
      } catch let error {
        logger.debug("error  : \(request) \(options) \(error)")
        throw error
      }
    }

    public func createCatalog(
      request: CreateCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      try await self._intercept(
        request: request,
        options: options,
        name: "createCatalog",
        action: {
          (r: CreateCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Catalog
          in
          return try await self.inner.createCatalog(request: r, options: o)
        })
    }

    public func deleteCatalog(
      request: DeleteCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteCatalog",
        action: {
          (r: DeleteCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Catalog
          in
          return try await self.inner.deleteCatalog(request: r, options: o)
        })
    }

    public func getCatalog(
      request: GetCatalogRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      try await self._intercept(
        request: request,
        options: options,
        name: "getCatalog",
        action: {
          (r: GetCatalogRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Catalog
          in
          return try await self.inner.getCatalog(request: r, options: o)
        })
    }

    public func listCatalogs(
      request: ListCatalogsRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listCatalogs",
        action: {
          (r: ListCatalogsRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.ListCatalogsResponse
          in
          return try await self.inner.listCatalogs(request: r, options: o)
        })
    }

    public func createDatabase(
      request: CreateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        name: "createDatabase",
        action: {
          (r: CreateDatabaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.createDatabase(request: r, options: o)
        })
    }

    public func deleteDatabase(
      request: DeleteDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteDatabase",
        action: {
          (r: DeleteDatabaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.deleteDatabase(request: r, options: o)
        })
    }

    public func updateDatabase(
      request: UpdateDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateDatabase",
        action: {
          (r: UpdateDatabaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.updateDatabase(request: r, options: o)
        })
    }

    public func getDatabase(
      request: GetDatabaseRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        name: "getDatabase",
        action: {
          (r: GetDatabaseRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.getDatabase(request: r, options: o)
        })
    }

    public func listDatabases(
      request: ListDatabasesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listDatabases",
        action: {
          (r: ListDatabasesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.ListDatabasesResponse
          in
          return try await self.inner.listDatabases(request: r, options: o)
        })
    }

    public func createTable(
      request: CreateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "createTable",
        action: {
          (r: CreateTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.createTable(request: r, options: o)
        })
    }

    public func deleteTable(
      request: DeleteTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "deleteTable",
        action: {
          (r: DeleteTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.deleteTable(request: r, options: o)
        })
    }

    public func updateTable(
      request: UpdateTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "updateTable",
        action: {
          (r: UpdateTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.updateTable(request: r, options: o)
        })
    }

    public func renameTable(
      request: RenameTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "renameTable",
        action: {
          (r: RenameTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.renameTable(request: r, options: o)
        })
    }

    public func getTable(
      request: GetTableRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        name: "getTable",
        action: {
          (r: GetTableRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.getTable(request: r, options: o)
        })
    }

    public func listTables(
      request: ListTablesRequest, options: GoogleCloudGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse {
      try await self._intercept(
        request: request,
        options: options,
        name: "listTables",
        action: {
          (r: ListTablesRequest, o: GoogleCloudGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.ListTablesResponse
          in
          return try await self.inner.listTables(request: r, options: o)
        })
    }
  }
}
