// Code generated by sidekick. DO NOT EDIT.
//
// Copyright 2026 Google LLC
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     https://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

import Foundation
#if canImport(FoundationNetworking)
  import FoundationNetworking
#endif
import GoogleWKT
@_spi(GoogleCloudInternal) import GoogleGax

extension Clients {
  final class MetastoreServiceRetry: MetastoreServiceStub {
    let inner: any MetastoreServiceStub
    let options: GoogleGax.ClientOptions

    public init(_ inner: any MetastoreServiceStub, options: GoogleGax.ClientOptions) {
      self.inner = inner
      self.options = options
    }

    func _intercept<Input, Output>(
      request: Input,
      options: GoogleGax.RequestOptions,
      idempotent: Swift.Bool,
      action: (Input, GoogleGax.RequestOptions) async throws -> Output,
    ) async throws -> Output {
      let loop = GoogleGax._RetryLoop(
        options: options, withDefault: self.options, idempotent: idempotent,
      )
      let attempt = { (attemptTimeout: Swift.Duration?) async throws -> Output in
        var attemptOptions = options
        attemptOptions.attemptTimeout = attemptTimeout
        return try await action(request, attemptOptions)
      }
      return try await loop.run(attempt: attempt)
    }

    public func createCatalog(
      request: CreateCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateCatalogRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Catalog
          in
          return try await self.inner.createCatalog(request: r, options: o)
        })
    }

    public func deleteCatalog(
      request: DeleteCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteCatalogRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Catalog
          in
          return try await self.inner.deleteCatalog(request: r, options: o)
        })
    }

    public func getCatalog(
      request: GetCatalogRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Catalog {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetCatalogRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Catalog
          in
          return try await self.inner.getCatalog(request: r, options: o)
        })
    }

    public func listCatalogs(
      request: ListCatalogsRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListCatalogsResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListCatalogsRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.ListCatalogsResponse
          in
          return try await self.inner.listCatalogs(request: r, options: o)
        })
    }

    public func createDatabase(
      request: CreateDatabaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateDatabaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.createDatabase(request: r, options: o)
        })
    }

    public func deleteDatabase(
      request: DeleteDatabaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteDatabaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.deleteDatabase(request: r, options: o)
        })
    }

    public func updateDatabase(
      request: UpdateDatabaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateDatabaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.updateDatabase(request: r, options: o)
        })
    }

    public func getDatabase(
      request: GetDatabaseRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Database {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetDatabaseRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Database
          in
          return try await self.inner.getDatabase(request: r, options: o)
        })
    }

    public func listDatabases(
      request: ListDatabasesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListDatabasesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListDatabasesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.ListDatabasesResponse
          in
          return try await self.inner.listDatabases(request: r, options: o)
        })
    }

    public func createTable(
      request: CreateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: CreateTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.createTable(request: r, options: o)
        })
    }

    public func deleteTable(
      request: DeleteTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: DeleteTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.deleteTable(request: r, options: o)
        })
    }

    public func updateTable(
      request: UpdateTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: UpdateTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.updateTable(request: r, options: o)
        })
    }

    public func renameTable(
      request: RenameTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: false,
        action: {
          (r: RenameTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.renameTable(request: r, options: o)
        })
    }

    public func getTable(
      request: GetTableRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.Table {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: GetTableRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.Table
          in
          return try await self.inner.getTable(request: r, options: o)
        })
    }

    public func listTables(
      request: ListTablesRequest, options: GoogleGax.RequestOptions
    ) async throws -> GoogleBigQueryBigLakeV1.ListTablesResponse {
      try await self._intercept(
        request: request,
        options: options,
        idempotent: true,
        action: {
          (r: ListTablesRequest, o: GoogleGax.RequestOptions) async throws
            -> GoogleBigQueryBigLakeV1.ListTablesResponse
          in
          return try await self.inner.listTables(request: r, options: o)
        })
    }
  }
}
